### ISSUE TITLE
rendre générique `useResourceSearch`

### ISSUE THREAD

**Issue by ccreusat** [edificeio/edifice-ui#120]
@jcbe-ode 

Est-ce qu'on rendrait pas générique le typage de `useResourceSearch` car pour le moment il est fait pour `ILinkerResource`.
Il utilise la recherche explorer

```
await odeServices
            .resource(appCode, resourceType)
            .searchContext(filters)
            .then((results) => results.resources);
```

mais le hook retourne en promesse un tableau de `ILinkerResource`.

```
return { resourceApplications, loadResources } as {
    resourceApplications: Array<App>;
    loadResources: (filters: GetContextParameters) => Promise<ILinkedResource[]>;
  };
```

Ce que je propose pour pouvoir récupérer des `IResource` : 

```
export const useResourceSearch = <T>(appCode: App) => {...}
```

retourne 

```
return { resourceApplications, loadResources } as {
    resourceApplications: Array<App>;
    loadResources: (filters: GetContextParameters) => Promise<T[]>;
  };
```

et à l'usage : 

```

// LinkerResource
const { loadResources } =
    useResourceSearch<ILinkedResource>(appCode);

// IResource
const { loadResources } =
    useResourceSearch<IResource>(appCode);
```

**Comment by jcbe-ode** [comment]
_Pour mémoire: je dresse l'état des lieux avant de réfléchir et répondre :)_

On dispose en ce moment de 2 API dans edifice-ts-client pour rechercher des ressources : 

* [l'API d'exploration](https://github.com/opendigitaleducation/edifice-ts-client/blob/78d4b541f80b469a179beedbff325503dfccca9e/src/ts/resources/ResourceService.ts#L28C23-L28C38) : pas encore supportée par toutes les applis, car elles nécessitent un dev backend pour indexer les ressources.

* [l'API de listing de ressources](https://github.com/opendigitaleducation/edifice-ts-client/blob/78d4b541f80b469a179beedbff325503dfccca9e/src/ts/resources/behaviours/AbstractBehaviourService.ts#L38) (celle intégrée dans `useResourceSearch`) : basée sur le rétro-engineering [des fonctions `loadResources()` des behaviours](https://github.com/opendigitaleducation/scrapbook/blob/80e33f360ef7dc0f16b87de0efa74e5b80206402/src/main/resources/public/ts/behaviours.ts#L63) historiques des applis.

Seule la première API devrait exister, la seconde étant vouée à disparaître car biaisée (pb de filtres, ordonnancement, pagination...).

Les 2 API se ressemblent, elles implémentent la même interface [IResourceService](https://github.com/opendigitaleducation/edifice-ts-client/blob/78d4b541f80b469a179beedbff325503dfccca9e/src/ts/resources/interface.ts#L7) => les `loadResources()` historiques mappent désormais les données trouvées sur un sous-ensemble du modèle de données de l'explorateur, `IResource` (à noter : c'est faux. En pratique c'est une extension, pas un sous-ensemble)

La 1ère API intègre sa propre registry;
La 2nde propose un service de plus haut niveau [SnippletService](https://github.com/opendigitaleducation/edifice-ts-client/blob/78d4b541f80b469a179beedbff325503dfccca9e/src/ts/services/SnipletsService.ts#L22), volontairement séparé des services standard de ts-client, car il permet de surcharger la registry du 1er. Et ne doit pas être utilisé ailleurs que dans le Linker.

Comme les applis seront adaptées petit à petit côté back, la seconde API va pouvoir aussi évoluer petit à petit, dans ts-client;
il suffira de supprimer la behaviour d'une appli migrée, et de supprimer la surcharge dans la registry, sans rien devoir modifier côté UI; en théorie... car côté UI, `useResourceSearch()` est actuellement biaisée :  elle utilise la 1ère API d'exploration, mais la données retournée est de type `ILinkedResource` au lieu de `IResource` (contenant un champ `path` en +); voir note précédente.

Quand toutes seront migrées, on pourra complètement supprimer la seconde API et remplacer l'interface du Linker par une interface d'exploration standard... C'était le plan imaginé initialement.
Au final, `useResourceSearch()` aurait gagné à être nommée `useLinkerSearch()`, car elle est fortement liée à l'UI du Linker.

**Comment by jcbe-ode** [comment]
La question est donc : 
* comment supprimer le type ILinkedResource, et faire en sorte que le Linker continue de fonctionner via l'API d'exploration standard.
* comment sécuriser l'usage de SnippletService, dans l'intervalle de temps où toutes les applis seront migrées.
et par extension, 
* comment mieux gérer la registry de `IResourceService`s ?

**Comment by ccreusat** [comment]
@jcbe-ode 
Effectivement, je voulais juste clarifier l'usage du hook, mais il faudra un plan pour retirer les services de Blog et Mindmap, et Mur collaboratif avec le portage React et pouvoir charger les services qui sont sur ts-client pour le moment depuis l'app cible et avoir un moyen de les charger ailleurs (à terme dans le linker par exemple)

On verra lundi, s'il faut des packages ou taper sur des scripts chargés dynamiquement et surtout où mettre le "service" d'une app migré dans l'explorateur
